name: build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  tests:
    name: Golang ${{ matrix.go }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go: ['1.14', '1.15']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -race $(go list ./...) -coverprofile=coverage.out -v > ./tests.out 2>&1 || true; cat ./tests.out

      - name: Upload Coverage report to CodeCov
        continue-on-error: true
        uses: codecov/codecov-action@v1 # https://github.com/codecov/codecov-action
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
          fail_ci_if_error: false
