name: build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  tests:
    name: Golang ${{ matrix.go }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14', '1.x']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Print golang version
        run: go version

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run gofmt
        run: $(exit $(gofmt -l . | wc -l))

      - name: Run gotest
        run: go test -v ./...
